apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::YOUR_AWS_ACCOUNT:role/eks-role-tensorwarp-prod-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - engineering:ops
      rolearn: arn:aws:iam::YOUR_AWS_ACCOUNT:role/tensorwarp-Lead
      username: devops
  mapUsers: |
    - userarn: arn:aws:iam::YOUR_AWS_ACCOUNT:user/tensorwarp
      username: tensorwarp
      groups:
        - system:masters
    - userarn: arn:aws:iam::YOUR_AWS_ACCOUNT:user/devops
      username: devops
      groups:
        - system:masters