---
##################################################
### STAGING (DEV/UAT) Environment tensorwarp ###
##################################################
apiVersion: v1
kind: Namespace
metadata:
  name: tensorwarp
  labels:
    app.kubernetes.io/name: tensorwarp
    app.kubernetes.io/instance: tensorwarp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tensorwarp-svcaccount
  namespace: tensorwarp
