##################################################
### STAGING (DEV/UAT) Environment tensorwarp ###
##################################################
apiVersion: v1
kind: Namespace
metadata:
  name: tensorwarp
  labels:
    app.kubernetes.io/name: tensorwarp
    app.kubernetes.io/instance: tensorwarp

---
apiVersion: v1
kind: Secret
metadata:
  name: tensorwarp-cred
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.8
    app.kubernetes.io/instance: tensorwarp-dev_db
    app.kubernetes.io/managed-by: Helm
  namespace: tensorwarp
type: Opaque
data:
  db-user: dXNlcm5hbWUK   # username
  db-pass: cGFzc3cwcmQK   # passw0rd
  db-host: MTI3LjAuMC4xCg==  # 127.0.0.1
