name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, zip, pdo, pdo_pgsql

      - name: Build and start Docker images
        run: |
          make build-test
          make start-test

      - name: Check running containers
        run: docker ps -a

      - name: Wait for database connection
        run: make wait-for-db

      - name: Run migrations and seeds
        run: |
          make drop-migrate
          make seed

      - name: Show framework version and additional info, PHP & Composer version
        run: make info

      - name: Run test suite
        run: make phpunit

      - name: Archive coverage data for Qodana
        uses: actions/upload-artifact@v3
        with:
          name: php-coverage-data
          path: reports/clover.xml

      - name: Run coding standard
        run: make ecs

      - name: Run codeSniffer
        run: make phpcs

      - name: Run PHPStan
        run: make phpstan

      - name: Run PHPInsights
        run: make phpinsights

      - name: Run PHP mess detector
        run: make phpmd

      - name: Run PHP copy-paste detector
        run: make phpcpd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Stop Docker images
        run: make stop-test
  