name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ['build-test', 'start-test', 'wait-for-db', 'drop-migrate', 'seed', 'info', 'phpunit', 'ecs', 'phpcs', 'phpstan', 'phpinsights', 'phpmd', 'phpcpd', 'stop-test']
    steps:
      - uses: actions/checkout@v4

      - name: Build and Start Docker Images
        run: make ${{ matrix.step }}

      - name: Database Setup
        run: |
          make wait-for-db
          make drop-migrate
          make seed

      - name: Testing
        run: |
          make phpunit
          make ecs
          make phpcs
          make phpstan
          make phpinsights
          make phpmd
          make phpcpd

      - name: Additional Checks
        run: make info

      - name: Archive Coverage Data for Qodana
        uses: actions/upload-artifact@v3
        with:
          name: php-coverage-data
          path: reports/clover.xml

      - name: Stop Docker Images
        run: make stop-test
  